services:
  - type: web
    name: nbd-crm-api
    runtime: python
    runtimeVersion: 3.13.1
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.1
